apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test-tektonplugin-1
  janus-idp.io/tekton: test-tektonplugin-1
  backstage.io/kubernetes-id: test-tektonplugin-1
  backstage.io/kubernetes-namespace: ai-rhdh-app 
  app.kubernetes.io/part-of: test-tektonplugin-1
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
